services:
  api:
    build: .
    image: aura-backend
    ports:
      - "9999:9999"
    environment:
      DB_PATH: /app/src/aura.db
    volumes:
      - ./src/aura.db:/app/src/aura.db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: aura-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/app/src/frontend
      - /app/src/frontend/node_modules
    environment:
      - VITE_API_URL=http://localhost:9999/api
