services:
  api:
    build: .
    image: aura-bacykend
    ports:
      - "9999:9999"
    environment:
      DB_PATH: /app/src/aura.db
    volumes:
      - ./src/aura.db:/app/src/aura.db

  frontend:
    build:
      context: ./src
      dockerfile: ../Dockerfile.frontend
      args:
        - FRONTEND_DIR=Web Interface for AURA Clinic (1)
    image: aura-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://api:9999/api
    depends_on:
      - api
